apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: bots
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
