name: Docker Image Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mars2dot/music_bot:latest .

      - name: Push Docker image
        run: docker push mars2dot/music_bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          installKubectl: true
          kubectlVersion: 'latest'

      - name: Decode kube-config
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kube-config.yaml

      - name: Configure kubectl
        run: |
          kubectl config use-context default --kubeconfig=kube-config.yaml

      - name: Deploy using Helm
        run: helm upgrade --install music-bot-$(git rev-parse --short HEAD) ./deploy
