name: Docker Image Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          maven-version: '3.8.7'

      - name: Build artifact
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mars2dot/music_bot:latest .

      - name: Push Docker image
        run: docker push mars2dot/music_bot:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl get pods

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Deploy using Helm
        run: |
          if helm ls -n bots | grep -q 'music-bot'; then
            echo "Release exists, upgrading..."
            helm delete music-bot -n bots
            kubectl get pods -n bots | grep 'music-bot' | awk '{print $1}' | xargs -I {} kubectl delete pod {} -n bots --force --grace-period=0
            helm install music-bot ./deploy --namespace bots
          else
            echo "Release does not exist, installing..."
            helm install music-bot ./deploy --namespace bots
          fi