name: Docker Image Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short-sha.outputs.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Get short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build artifact
        run: mvn clean install -U -DskipTests

      - name: Login to Harbor
        run: docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.HARBOR_URL }}/bots/music_bot:${{ steps.short-sha.outputs.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.HARBOR_URL }}/bots/music_bot:${{ steps.short-sha.outputs.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl get pods

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Deploy using Helm
        run: |
          helm upgrade --install music-bot ./k8s/MusicBot \
            --namespace bots \
            --set image.repository=${{ secrets.HARBOR_URL }}/bots/music_bot \
            --set image.tag=${{ needs.build.outputs.short_sha }}
