name: Docker Image Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mars2dot/music_bot:latest .

      - name: Push Docker image
        run: docker push mars2dot/music_bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/kubernetes-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Configure kubectl
        run: |
          kubectl config use-context ${{ secrets.CLUSTER_NAME }}  
          
      - name: Deploy using Helm
        run: | 
          cat kube-config.yaml 
          kubectl config view
          kubectl cluster-info
          kubectl get nodes
          helm upgrade --install music-bot ./deploy
      
