name: Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t mars2dot/music_bot:latest .

    - name: Push Docker image
      run: docker push mars2dot/music_bot:latest

  deploy:    
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        installKubectl: true
        kubectlVersion: 'latest' 

    - name: Configure kubectl
      run: |
        kubectl config set-cluster ${{ secrets.CLUSTER_NAME }} \
          --server=${{ secrets.KUBERNETES_SERVER_URL }} \
          --insecure-skip-tls-verify=true 
        kubectl config set-context default --cluster=${{ secrets.CLUSTER_NAME }}
        kubectl config use-context default

    - name: Deploy using Helm
      run: ls && helm upgrade --install music_bot-$(git rev-parse --short HEAD) ./deploy


